{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-types
  version: {{ version }}

source:
  path: ../..
build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-bio {{ scikit_bio }}
    - numpy
    # TODO: revert
    # - pandas {{ pandas }}
    - pandas
    - biom-format {{ biom_format }}
    - ijson
    - h5py >=3.6.0
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - pytest
    - qiime2 >={{ qiime2 }}

  imports:
    - q2_types
    - qiime2.plugins.types

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
