{% set data = load_setup_py_data() %}

package:
  name: q2-types
  version: {{ data.get('version') }}

source:
  path: ../..
build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools
    - scikit-bio
    - qiime2 2017.3.*
    - pandas
    - biom-format >=2.1.5,<2.2.0
    - ijson
    - h5py

  run:
    - python 3.5*
    - setuptools
    - scikit-bio
    - qiime2 2017.3.*
    - pandas
    - biom-format >=2.1.5,<2.2.0
    - ijson
    - h5py

test:
  imports:
    - q2_types
    - qiime2.plugins.types

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
