{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-types
  version: {{ version }}

source:
  path: ../..
build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - scikit-bio >=0.5.4
    # TODO: unset this pin once pandas 0.24.x is sorted out upstream
    - pandas 0.23.4
    - numpy
    - blas=*=openblas
    - biom-format >=2.1.5,<2.2.0
    - ijson
    - h5py
    - qiime2 {{ release }}.*

test:
  imports:
    - q2_types
    - qiime2.plugins.types

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
